# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f93debb3b47b474366163b959671d92c7b6f663ffbc7993e738e2b522ca4b5d314ee652266c5cba1197f1c695b985751edd508b9ded5c72b9a73fc784db39c

test:
  secret_key_base: b5f3110945887e6db935d87515b08297849f09bcdf6400028a673a980de9eca82eea861e07d4cffdce17768aec0e9efb8db4abd837caa44b7c3647522d67b38a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
